// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZH1ntw11eyRTzJBJwP4CljfUlUgp-ae0',
    appId: '1:850918154320:web:79188090aeaf8a09ac7155',
    messagingSenderId: '850918154320',
    projectId: 'upload-pets4life',
    authDomain: 'upload-pets4life.firebaseapp.com',
    storageBucket: 'upload-pets4life.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARKkUKdUege6pscIHcJyrwHLRTw1BTCnE',
    appId: '1:850918154320:android:de5589ed97774cb0ac7155',
    messagingSenderId: '850918154320',
    projectId: 'upload-pets4life',
    storageBucket: 'upload-pets4life.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNWLU1Fgz4-KRVV_bHfRDsBbkkbgB7pZY',
    appId: '1:850918154320:ios:2f0533bb039b54dbac7155',
    messagingSenderId: '850918154320',
    projectId: 'upload-pets4life',
    storageBucket: 'upload-pets4life.appspot.com',
    iosBundleId: 'com.example.petcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNWLU1Fgz4-KRVV_bHfRDsBbkkbgB7pZY',
    appId: '1:850918154320:ios:d83acb0ca44523fcac7155',
    messagingSenderId: '850918154320',
    projectId: 'upload-pets4life',
    storageBucket: 'upload-pets4life.appspot.com',
    iosBundleId: 'com.example.petcare.RunnerTests',
  );
}
